#!/usr/bin/env node
/**
 * Generate the installable dsh-Friend bundle from its declarative membership
 * list. The aggregate package owns no behavior itself; it only pins the exact
 * Cordis patch and workspace dependency set that DSH installs together.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { parse } from 'yaml'

const DEFAULT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const AGGREGATE_PACKAGE = 'dsh-friend-all'
const AGGREGATE_NAME = '@wish233/dsh-friend-all'
const FRIEND_PACKAGE_PREFIX = '@wish233/dsh-friend-'

function usage() {
  return 'Usage: node scripts/aggregate.mjs [--check] [--root <workspace-root>]'
}

export function parseArgs(argv) {
  let root = DEFAULT_ROOT
  let check = false

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--check') {
      check = true
      continue
    }
    if (arg === '--root') {
      const value = argv[index + 1]
      if (value === undefined || value.startsWith('-')) {
        throw new Error('--root requires a workspace path')
      }
      root = resolve(value)
      index += 1
      continue
    }
    if (arg === '--help' || arg === '-h') {
      return { help: true, root, check }
    }
    throw new Error(`Unknown argument: ${arg}`)
  }

  return { help: false, root, check }
}

function assertStringArray(value, field) {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string' || entry.length === 0)) {
    throw new Error(`${field} must be a string array`)
  }
  return value
}

function assertUnique(values, field) {
  if (new Set(values).size !== values.length) {
    throw new Error(`${field} must not repeat package names`)
  }
  return values
}

function pluginId(packageName) {
  const slash = packageName.lastIndexOf('/')
  const id = slash === -1 ? packageName : packageName.slice(slash + 1)
  if (id.length === 0) {
    throw new Error(`cannot derive plugin id from ${packageName}`)
  }
  return id
}

function renderPatch(rows) {
  const items = rows.map((row) => [
    `    - id: ${row.id}`,
    `      name: '${row.name}'`,
  ].join('\n'))

  return [
    '# Generated by scripts/aggregate.mjs; do not edit by hand.',
    '',
    '- insert:',
    items.join('\n\n'),
    '',
  ].join('\n')
}

function renderManifest(manifest, deps) {
  const dependencies = { ...(manifest.dependencies ?? {}) }
  for (const dependency of Object.keys(dependencies)) {
    if (dependency.startsWith(FRIEND_PACKAGE_PREFIX)) {
      delete dependencies[dependency]
    }
  }
  for (const dependency of deps) {
    dependencies[dependency] = 'workspace:*'
  }

  return `${JSON.stringify({ ...manifest, dependencies }, null, 2)}\n`
}

async function readText(path) {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return null
    }
    throw error
  }
}

async function listFeaturePackages(root) {
  const packagesDir = join(root, 'packages')
  const entries = await readdir(packagesDir, { withFileTypes: true })
  const features = []

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name === AGGREGATE_PACKAGE) {
      continue
    }

    const manifestPath = join(packagesDir, entry.name, 'package.json')
    const text = await readText(manifestPath)
    if (text === null) {
      continue
    }

    const manifest = JSON.parse(text)
    if (manifest === null || typeof manifest !== 'object' || typeof manifest.name !== 'string') {
      throw new Error(`${entry.name}/package.json must declare a string name`)
    }
    features.push({ dir: entry.name, name: manifest.name })
  }

  return features.sort((left, right) => left.name.localeCompare(right.name))
}

function summarizeDiff(actual, expected, label) {
  const current = (actual ?? '').split('\n')
  const next = expected.split('\n')
  const lines = [`--- ${label} (checked-in)`, `+++ ${label} (generated)`]
  const max = Math.max(current.length, next.length)
  let shown = 0

  for (let index = 0; index < max && shown < 20; index += 1) {
    if (current[index] === next[index]) {
      continue
    }
    if (current[index] !== undefined) {
      lines.push(`- ${current[index]}`)
    }
    if (next[index] !== undefined) {
      lines.push(`+ ${next[index]}`)
    }
    shown += 1
  }

  if (shown === 20) {
    lines.push('  ...')
  }
  return lines.join('\n')
}

export async function aggregate(root) {
  const allDir = join(root, 'packages', AGGREGATE_PACKAGE)
  const aggregatePath = join(allDir, 'aggregate.yml')
  const manifestPath = join(allDir, 'package.json')
  const patchPath = join(allDir, 'cordis.patch.yml')

  const config = parse(await readFile(aggregatePath, 'utf8'))
  if (config === null || typeof config !== 'object') {
    throw new Error('packages/dsh-friend-all/aggregate.yml must be a YAML object')
  }

  const patchFrom = assertUnique(assertStringArray(config.patchFrom, 'aggregate.yml patchFrom'), 'aggregate.yml patchFrom')
  const deps = assertUnique(assertStringArray(config.deps, 'aggregate.yml deps'), 'aggregate.yml deps')
  const features = await listFeaturePackages(root)
  const known = new Set(features.map((feature) => feature.name))

  for (const name of [...patchFrom, ...deps]) {
    if (name === AGGREGATE_NAME) {
      throw new Error('aggregate.yml must not list the aggregate package itself')
    }
    if (!known.has(name)) {
      throw new Error(`aggregate.yml lists unknown package: ${name}`)
    }
  }

  const missingFromPatch = features.filter((feature) => !patchFrom.includes(feature.name)).map((feature) => feature.name)
  const missingFromDeps = features.filter((feature) => !deps.includes(feature.name)).map((feature) => feature.name)
  if (missingFromPatch.length > 0 || missingFromDeps.length > 0) {
    const details = [
      missingFromPatch.length > 0 ? `patchFrom: ${missingFromPatch.join(', ')}` : null,
      missingFromDeps.length > 0 ? `deps: ${missingFromDeps.join(', ')}` : null,
    ].filter(Boolean)
    throw new Error(`unregistered feature package(s): ${details.join('; ')}`)
  }

  const rows = patchFrom.map((name) => ({ id: pluginId(name), name }))
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  return {
    manifestPath,
    patchPath,
    manifest: renderManifest(manifest, deps),
    patch: renderPatch(rows),
  }
}

export async function run(options) {
  const generated = await aggregate(options.root)
  const currentPatch = await readText(generated.patchPath)
  const currentManifest = await readText(generated.manifestPath)
  const drifted = []
  if (currentPatch !== generated.patch) {
    drifted.push({
      label: 'packages/dsh-friend-all/cordis.patch.yml',
      actual: currentPatch,
      expected: generated.patch,
      path: generated.patchPath,
    })
  }
  if (currentManifest !== generated.manifest) {
    drifted.push({
      label: 'packages/dsh-friend-all/package.json',
      actual: currentManifest,
      expected: generated.manifest,
      path: generated.manifestPath,
    })
  }

  if (options.check) {
    if (drifted.length > 0) {
      console.error(`aggregate drift: ${drifted.map((file) => file.label).join(', ')}`)
      for (const file of drifted) {
        console.error(summarizeDiff(file.actual, file.expected, file.label))
      }
      process.exitCode = 1
      return
    }
    console.log('aggregate is up to date')
    return
  }

  if (drifted.length === 0) {
    console.log('aggregate is up to date')
    return
  }

  for (const file of drifted) {
    await writeFile(file.path, file.expected, 'utf8')
  }
  console.log(`generated ${drifted.map((file) => file.label).join(', ')}`)
}

async function main() {
  try {
    const options = parseArgs(process.argv.slice(2))
    if (options.help) {
      console.log(usage())
      return
    }
    await run(options)
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}

const invocation = process.argv[1] === undefined ? undefined : pathToFileURL(resolve(process.argv[1])).href
if (import.meta.url === invocation) {
  await main()
}
